// import {
//   Cloud,
//   CloudFog,
//   CloudLightning,
//   CloudRain,
//   CloudSnow,
//   CloudSun,
//   IconProps,
//   Question,
//   Sun,
// } from "phosphor-react";

export const weatherCode = {
  0: { icon: "Sun", desc: "Sunny" },
  1: { icon: "CloudSun", desc: "Mainly sunny" },
  2: { icon: "CloudSun}", desc: "Part cloudy" },
  3: { icon: "Cloud}", desc: "Cloudy" },
  45: { icon: "Cloud", desc: "Foggy" },
  48: { icon: "CloudFog", desc: "Foggy depositing rime" },
  51: { icon: "CloudFog", desc: "Light drizzle" },
  53: { icon: "CloudRain", desc: "Moderate drizzle" },
  55: { icon: "CloudRain", desc: "Dense drizzle" },
  56: { icon: "CloudSnow", desc: "Light freezing drizzle" },
  57: { icon: "CloudSnow", desc: "Dense freezing drizzle" },
  61: { icon: "CloudRain", desc: "Light rain" },
  63: { icon: "CloudRain", desc: "Moderate rain" },
  65: { icon: "CloudRain", desc: "Heavy rain" },
  66: { icon: "CloudSnow", desc: "Light freezing rain" },
  67: { icon: "CloudSnow", desc: "Heavy freezing rain" },
  71: { icon: "CloudSnow", desc: "Light snow fall" },
  73: { icon: "CloudSnow", desc: "Moderate snow fall" },
  75: { icon: "CloudSnow", desc: "Heavy snow fall" },
  77: { icon: "CloudSnow", desc: "Snow grains" },
  80: { icon: "CloudRain", desc: "Light rain showers" },
  81: { icon: "CloudRain", desc: "Moderate rain showers" },
  82: { icon: "CloudRain", desc: "Violent rain showers" },
  85: { icon: "CloudSnow", desc: "Light snow showers" },
  86: { icon: "CloudSnow", desc: "Heavy snow showers" },
  95: { icon: "CloudLightning", desc: "Thunderstorm" },
  96: { icon: "CloudLightning", desc: "Thunderstorm with light hail" },
  99: { icon: "CloudLightning", desc: "Thunderstorm with heavy hail" },
};
