// import {
//   Cloud,
//   CloudFog,
//   CloudLightning,
//   CloudRain,
//   CloudSnow,
//   CloudSun,
//   IconProps,
//   Question,
//   Sun,
// } from "phosphor-react";

export const weatherCode = {
  0: { icon: "Sun", desc: "Soleil" },
  1: { icon: "CloudSun", desc: "Soleil" },
  2: { icon: "CloudSun}", desc: "Éclaircies" },
  3: { icon: "Cloud}", desc: "Nuages" },
  45: { icon: "Cloud", desc: "Brouillard" },
  48: { icon: "CloudFog", desc: "Givre" },
  51: { icon: "CloudFog", desc: "Bruine" },
  53: { icon: "CloudRain", desc: "Bruine" },
  55: { icon: "CloudRain", desc: "Bruine" },
  56: { icon: "CloudSnow", desc: "Pluie verglaçante" },
  57: { icon: "CloudSnow", desc: "Pluie verglaçante" },
  61: { icon: "CloudRain", desc: "Pluie" },
  63: { icon: "CloudRain", desc: "Pluie" },
  65: { icon: "CloudRain", desc: "Pluie" },
  66: { icon: "CloudSnow", desc: "Givre" },
  67: { icon: "CloudSnow", desc: "Givre" },
  71: { icon: "CloudSnow", desc: "Neige" },
  73: { icon: "CloudSnow", desc: "Neige" },
  75: { icon: "CloudSnow", desc: "Neige" },
  77: { icon: "CloudSnow", desc: "Grêle" },
  80: { icon: "CloudRain", desc: "Averses" },
  81: { icon: "CloudRain", desc: "Averses" },
  82: { icon: "CloudRain", desc: "Averses" },
  85: { icon: "CloudSnow", desc: "Neige" },
  86: { icon: "CloudSnow", desc: "Neige" },
  95: { icon: "CloudLightning", desc: "Orage" },
  96: { icon: "CloudLightning", desc: "Orage" },
  99: { icon: "CloudLightning", desc: "Orage" },
};
